### ISSUE TITLE
Labels

### ISSUE THREAD

**Issue by GraceXu182** [shenjianbing/SubMarkov-Random-Walk-for-Image-Segmentation-#1]
Thanks for sharing the code with us. But when I attempted to use another example picture to run this program, I first made a label image and save it to the scribbles folder. For my lable image, I apply red color to mark the plane, and blue color for the background. However, "seed_generation" function will generate a empty 3D L  cell array for my new label image. Could you please help me figure out this problem?

**Comment by feifeizuo** [comment]
@GraceXu182 I guess you may have saved the label image in jpg format (with compression), you can try saving the label image in png format.

**Comment by GraceXu182** [comment]
Thanks for you reply! I will try your suggestion.
